version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1
  terraform: smelton01/terraform@dev:bbe4c076317f74548362e8cc7928b0d2a227ca08

commands:
  install_terraform:
    parameters:
      tf_version:
        type: string
        default: "1"
    steps:
      - terraform/install:
          terraform_version: << parameters.tf_version >>

jobs:
  test-something:
    docker:
      - image: cimg/base:2022.03

    steps:
      - checkout
      - run:
          name: Set terraform version env from file
          command: |
            TF_VERSION=$(cat .terraform_version)
            echo "Terrform version: ${TF_VERSION}"
            echo "export TF_VERSION=${TF_VERSION}" >> $BASH_ENV
      - run:
          name: Check env set
          command: |
            echo "Terraform version: ${TF_VERSION}"

      - install_terraform:
          tf_version: 1.8.3

      - install_terraform:
          tf_version: TF_VERSION

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters: *filters
      - orb-tools/publish:
          orb-name: smelton01/terraform
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/lint, orb-tools/review, orb-tools/pack]
          # Use a context to hold your publishing token.
          context: orb-publisher
          github-token: GHI_TOKEN
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
      - test-something
